//Source system constants
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const UPDATE_MODE = 'UPDATE_MODE';
export const UPDATE_SOURCE_SYSTEM_FIELD_VALUE = 'UPDATE_SOURCE_SYSTEM_FIELD_VALUE';
export const RESET_SOURCE_SYSTEM_FIELD_VALUES = 'RESET_SOURCE_SYSTEM_FIELD_VALUES';
export const UPDATE_ALL_SOURCE_SYSTEM_FIELD_VALUES = 'UPDATE_ALL_SOURCE_SYSTEM_FIELD_VALUES';
export const UPDATE_SS_TABLE_DATA = 'UPDATE_SS_TABLE_DATA';
export const UPDATE_TABLE_DATA = 'UPDATE_TABLE_DATA';
//Data Asset constants
export const OPEN_DA_DIALOGUE = 'OPEN_DA_DIALOGUE';
export const CLOSE_DA_DIALOGUE = 'CLOSE_DA_DIALOGUE';
export const UPDATE_DA_MODE = 'UPDATE_DA_MODE';
export const UPDATE_DATA_ASSET_FIELD_VALUE = 'UPDATE_DATA_ASSET_FIELD_VALUE';
export const UPDATE_ASSET_INFO_FIELD_VALUE = 'UPDATE_ASSET_INFO_FIELD_VALUE';
export const UPDATE_INGESTION_FIELD_VALUES = 'UPDATE_INGESTION_FIELD_VALUES';
export const UPDATE_COLUMN_ATTRIBUTES_DATA = 'UPDATE_COLUMN_ATTRIBUTES_DATA';
export const UPDATE_DQ_RULES_FIELD = 'UPDATE_DQ_RULES_FIELD';
export const UPDATE_ALL_DATA_ASSET_FIELD_VALUES = 'UPDATE_ALL_DATA_ASSET_FIELD_VALUES';
export const RESET_DATA_ASSET_FIELD_VALUES = 'RESET_DATA_ASSET_FIELD_VALUES';
export const UPDATE_DA_TABLE_FLAG = 'UPDATE_DA_TABLE_FLAG';
export const UPDATE_DA_TABLE_DATA = 'UPDATE_DA_TABLE_DATA';
export const UPDATE_SELECTED_ROW = 'UPDATE_SELECTED_ROW';
export const VALIDATE_COLUMN_ATTRIBUTES_DATA = 'VALIDATE_COLUMN_ATTRIBUTES_DATA';

// Lake Destination Constants
export const UPDATE_LAKE_DESTINATION_FIELD_VALUE = 'UPDATE_LAKE_DESTINATION_FIELD_VALUE';
export const UPDATE_ALL_LAKE_DESTINATION_FIELD_VALUES = 'UPDATE_ALL_LAKE_DESTINATION_FIELD_VALUES';
export const RESET_LAKE_DESTINATION_FIELD_VALUES = 'RESET_LAKE_DESTINATION_FIELD_VALUES';
export const UPDATE_LAKE_DESTINATION_TABLE_FETCH_DATA_FLAG = 'UPDATE_LAKE_DESTINATION_TABLE_FETCH_DATA_FLAG';
export const UPDATE_LAKE_DESTINATION_TABLE_DATA = 'UPDATE_LAKE_DESTINATION_TABLE_DATA';
// export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';