export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const UPDATE_MODE = 'UPDATE_MODE';
export const UPDATE_SOURCE_SYSTEM_FIELD_VALUE = 'UPDATE_SOURCE_SYSTEM_FIELD_VALUE';
export const RESET_SOURCE_SYSTEM_FIELD_VALUES = 'RESET_SOURCE_SYSTEM_FIELD_VALUES';
export const UPDATE_ALL_SOURCE_SYSTEM_FIELD_VALUES = 'UPDATE_ALL_SOURCE_SYSTEM_FIELD_VALUES';
// export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';